### PR TITLE
Fix import path

### PR DESCRIPTION
**Pull request by jacyzon**
fix wrong import path e.g.
https://github.com/paz-sh/paz.sh/blob/9c7f2052fff/Godeps/_workspace/src/github.com/digitalocean/godo/godo.go#L15

### CODE REVIEW

**Comment by lukebond** [comment]
@tomgco can you review/merge please?

**Comment by lukebond** [comment]
Thanks very much @Jacyzon :)

**Comment by tomgco** [comment]
LGTM!

**Comment by lukebond** [comment]
:+1:

**Pull request merged**
